# This is a TOML document

title = "MetaLogo webserver configure example"

example_path = 'MetaLogo/examples'
output_png_path = 'MetaLogo/figure_output'
output_fa_path = 'MetaLogo/sequence_input'
config_path = 'MetaLogo/configs'
log_path = 'MetaLogo/logs'
max_seq_limit = 200000
max_seq_len = 200
max_input_size = 5242880
google_analytics_id = 'G-0EZX46EYE9'
baidu_tongji_id = '53d867057aa25d8e9cf8e04221f009f8'

#bins
clustalo_bin = 'MetaLogo/bins/clustalo'
rate4site_bin = 'MetaLogo/bins/bin/rate4site'
treecluster_bin  = '/home/achen/anaconda3/envs/dash2/bin/TreeCluster.py'

sqlite3_db = 'MetaLogo/db/metalogo.db'
