# This is a TOML document

title = "MetaLogo webserver configure example"

example_path = 'MetaLogo/examples'
output_png_path = 'MetaLogo/figure_output'
output_fa_path = 'MetaLogo/sequence_input'
config_path = 'MetaLogo/configs'
log_path = 'MetaLogo/logs'
group_limit = 20
max_seq_limit = 200000
max_seq_limit_auto = 20000
max_seq_len = 600
max_input_size = 5242880
google_analytics_id = 'G-0EZX46EYE9'
baidu_tongji_id = '53d867057aa25d8e9cf8e04221f009f8'

#bins
clustalo_bin = '/usr/bin/clustalo'
fasttree_bin = '/usr/bin/FastTree'
fasttreemp_bin = '/usr/bin/FastTreeMP'
treecluster_bin  = 'TreeCluster.py'

sqlite3_db = 'MetaLogo/db/metalogo.db'
