# This is a TOML document

title = "MetaLogo webserver configure example"

example_path = 'examples'
output_png_path = 'figure_output'
output_fa_path = 'sequence_input'
config_path = 'configs'
log_path = 'logs'
